name: Check for updates and notify
on:
  schedule:
    - cron: '29 * * * *'  # Every hour

jobs:
  build:
    name: Build TeX
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2

      - name: Prepare Google Drive token
        run: 'echo "$YOU_THEE_DRIVE_TOKENS_JSON" > tokens.json'
        shell: bash
        env:
          YOU_THEE_DRIVE_TOKENS_JSON: ${{ secrets.YOU_THEE_DRIVE_TOKENS_JSON }}

      - name: Compile and build
        run: yarn install && yarn run build

      - name: Execute
        run: yarn run run
        env:
          YOU_THEE_ACCOUNT: ${{ secrets.YOU_THEE_ACCOUNT }}
          YOU_THEE_PASSWORD: ${{ secrets.YOU_THEE_PASSWORD }}
          YOU_THEE_SLACK_BOT_USER_TOKEN: ${{ secrets.YOU_THEE_SLACK_BOT_USER_TOKEN }}
          YOU_THEE_SLACK_CHANNEL_ID: ${{ secrets.YOU_THEE_SLACK_CHANNEL_ID }}
          YOU_THEE_DRIVE_CLIENT_ID: ${{ secrets.YOU_THEE_DRIVE_CLIENT_ID }}
          YOU_THEE_DRIVE_CLIENT_SECRET: ${{ secrets.YOU_THEE_DRIVE_CLIENT_SECRET }}
          YOU_THEE_DRIVE_MASTER_FOLDER_ID: ${{ secrets.YOU_THEE_DRIVE_MASTER_FOLDER_ID }}
          YOU_THEE_DRIVE_SHARED_FOLDER_ID: ${{ secrets.YOU_THEE_DRIVE_SHARED_FOLDER_ID }}
          YOU_THEE_DRIVE_DATA_STORE_ID: ${{ secrets.YOU_THEE_DRIVE_DATA_STORE_ID }}
