name: Check for updates and notify
on:
  schedule:
    - cron: '34 * * * *'  # Every hour
  push:
    branches:
      - develop-actions

jobs:
  build:
    name: Check for updates
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2

      - name: Prepare Google Drive token
        run: 'echo "$YOU_THEE_DRIVE_TOKENS_JSON" > tokens.json'
        shell: bash
        env:
          YOU_THEE_DRIVE_TOKENS_JSON: ${{ secrets.YOU_THEE_DRIVE_TOKENS_JSON }}

      - name: Prepare other environmental variables
        run: 'echo "$YOU_THEE_ENV" > .env'
        shell: bash
        env:
          YOU_THEE_ENV: ${{ secrets.YOU_THEE_ENV }}

      - name: Compile and build
        run: yarn install && yarn run build

      - name: Execute
        run: yarn run run
        env:
          YOU_THEE_ACCOUNT: ${{ secrets.YOU_THEE_ACCOUNT }}
          YOU_THEE_PASSWORD: ${{ secrets.YOU_THEE_PASSWORD }}
